### ISSUE TITLE
Failed to set locale, defaulting to C.UTF-8

### ISSUE THREAD

**Issue by rhmk** [linux-system-roles/sap-preconfigure#95] opened 2020-09-21 15:04 UTC
On a fresh installed linux system  I ran into an issue with languages that causes issues with the locales:
```
[root@dhcp134 ~]# yum needs-restarting -r
Failed to set locale, defaulting to C.UTF-8
[...]
```
langpack-en and glibc-langpack-en was installed
But I needed to install  glibc-all-langpacks to get rid of the message

It is most likely due to some locales passed through by ssh

Consider to  add  glibc-all-langpacks for fixing the issue

**Comment by berndfinger** [comment] 2020-12-21 11:52
I could reproduce the issue. The issue can happen if one of the glibc-langpack-?? locales shown in the output of the "locale" command is not installed. In my case, it was glibc-langpack-de. The output of the "locale" command contained:
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
while all other variables except LC_ALL were set to "en_US.UTF-8".
Variable LC_ALL was empty.

Maybe the de_DE.UTF-8 locale was used because I had selected a German keyboard, or because I the timezone is "Europe/Berlin (CET, +0100)"

Besides installing glibc-all-langpacks, I could solve the issue by:
- setting LC_ALL to "en_US.UTF-8" or "C" before calling yum needs-restarting -r
- installing glibc-langpack-de before calling yum needs-restarting -r

As the error message is not affecting the behavior of the needs-restarting detection, I will probably set the status of this issue to "will not fix".

**Comment by berndfinger** [comment] 2022-01-28 11:58
Development and maintenance of this software has stopped. The role [sap_general_preconfigure](https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_general_preconfigure) replaces it. I am closing this issue now as per my last reply.

**Closed by berndfinger** 2022-01-28 11:58 UTC
Labels: 3_enhancement
